///news

export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';

export const FETCH_NEW = 'FETCH_NEW';

///helper

export const INDEX_CHANGE_HANDLER = 'INDEX_CHANGE_HANDLER';
export const HANDLE_NAVIGATION_REQUEST = 'HANDLE_NAVIGATION_REQUEST';
export const HANDLE_FEED_SCREEN_CLICK = ' HANDLE_FEED_SCREEN_CLICK';
export const SHOW_MENU_BAR = 'SHOW_MENU_BAR';
export const NIGHT_MODE_TOOGLE = 'NIGHT_MODE_TOGGLE';

//category
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
